name: Create Release Zip

on:
  push:
    tags:
      - 'v*'  # 當推送標籤時觸發

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Create zip without root folder
      run: |
        git archive --format zip --prefix="" -o server_resource_pack.zip HEAD

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        # 確保 'files' 參數指向你固定的 ZIP 檔名
        files: "server_resource_pack.zip" # 與上面 'git archive' 的輸出檔名一致
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
